---
- name: Test SSH connection to Juniper devices using SSH key
  hosts: swt1
  gather_facts: no
  connection: local

  tasks:
    - name: Exécution de la commande 
      juniper.device.config:
        config_mode: "private"
        timeout: "90"
        load: "set"
        lines:
           - "set vlans semaphore.777 vlan-id 777"
           - "set vlans sema.888 vlan-id 888"
           
      register: response

    - name: "Print the response"
      debug:
        var: response
  

