---
- name: Get device information
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Get software and uptime information
      juniper.device.command:        
        commands: 
          - "show version"        
          - "show system uptime"
      register: junos_result

    - name: Print response
      ansible.builtin.debug:
        var: junos_result
